#!/usr/bin/env bash

nix-lookup () {
	local EXPR
	EXPR="\"\${(import <nixpkgs> {}).pkgs.$1}\"" 
	nix-instantiate --eval -E "${EXPR}" | sed 's:"::g'
}

XKB_BINDIR="$(nix-lookup xorg.xkbcomp)/bin"
XKB_DIR="$(nix-lookup xorg.xkeyboardconfig)/etc/X11/xkb"

FMM="$(nix-lookup xorg.fontmiscmisc)/lib/X11/fonts/misc"
FCM="$(nix-lookup xorg.fontcursormisc)/lib/X11/fonts/misc"

export XKB_BINDIR

Xnest                      \
    -display ":0" ":1"     \
    -xkbdir "$XKB_DIR"     \
    -geometry "1024x768"   \
    -fp "${FMM},${FCM}"    \
    -depth 24              \
    -auth "/tmp/hsdm.auth"
